spring.application.name=store
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/Store
spring.datasource.username=postgres
spring.datasource.password=zaidkassem
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
